services:
  - type: web
    name: hello-monorepo-backend
    plan: starter
    branch: main
    env: python
    repo: https://github.com/jeremy-render/hello-monorepo.git
    rootDir: backend
    buildCommand: pip install -r requirements.txt
    startCommand: python app.py
    envVars:
      - fromGroup: hello-monorepo-envgroup
      - key: PYTHON_VERSION
        value: 3.10.8

  - type: web
    name: hello-monorepo-frontend
    branch: main
    env: static
    repo: https://github.com/jeremy-render/hello-monorepo.git
    rootDir: frontend
    staticPublishPath: .
    envVars:
      - fromGroup: hello-monorepo-envgroup
      - key: BACKEND_HOST
        fromService: 
          name: hello-monorepo-backend
          type: web
          property: host